Repository JirkaDellOro/Computergrafik.Online, pull requests merged in 2020-07, with the labels that each got.

#208 #204 - added information texts for videos, inserted interactions
  Interaktionen/12-Texturen/12.2_Textur-Einleitung/index.html
  Interaktionen/12-Texturen/12.5_UV-Mapping/index.html
  collage.png
  docs/assets/dist/css/main.css
  docs/assets/dist/data/data.json
  docs/assets/dist/interactions/12-Texturen/12.2_Textur-Einleitung/index.html
  docs/assets/dist/interactions/12-Texturen/12.5_UV-Mapping/index.html
  docs/assets/dist/js/youtube.js
  webpage/assets/dist/interactions/12-Texturen/12.2_Textur-Einleitung/index.html
  webpage/assets/dist/interactions/12-Texturen/12.5_UV-Mapping/index.html
Labels: review

#218 fixed most vulnerabilites
  docs/package-lock.json
  docs/package.json
Labels: review

#220 Sarah: Hierarchie + Interpolationskurve
  Interaktionen/08-Szenenaufbau/8.7 Hierachie/assets/Animation_Rotation_Origin_am_Gelenk.mp4
  Interaktionen/08-Szenenaufbau/8.7 Hierachie/assets/Animation_Rotation_Origin_im_Ursprung.mp4
  Interaktionen/08-Szenenaufbau/8.7 Hierachie/assets/Still.jpg
  Interaktionen/08-Szenenaufbau/8.7 Hierachie/main.css
  Interaktionen/08-Szenenaufbau/8.7 Hierachie/main.html
  Interaktionen/08-Szenenaufbau/8.7 Hierachie/main.js
  Interaktionen/08-Szenenaufbau/8.7 Hierachie/main.js.map
  Interaktionen/08-Szenenaufbau/8.7 Hierachie/main.ts
  Interaktionen/13-Animation/interpolationskurve/assets/square.jpg
  Interaktionen/13-Animation/interpolationskurve/main.css
  Interaktionen/13-Animation/interpolationskurve/main.html
  Interaktionen/13-Animation/interpolationskurve/main.js
Labels: review

#221 inserted hierarchie and interpolationscurves into datat json
  Interaktionen/13-Animation/13.2 Interpolationskurven/assets/square.jpg
  Interaktionen/13-Animation/13.2 Interpolationskurven/main.css
  Interaktionen/13-Animation/13.2 Interpolationskurven/main.html
  Interaktionen/13-Animation/13.2 Interpolationskurven/main.js
  docs/assets/dist/data/data.json
  docs/assets/dist/interactions/08-Szenenaufbau/8.7 Hierachie/Animation Rotation Origin am Gelenk.mp4
  docs/assets/dist/interactions/08-Szenenaufbau/8.7 Hierachie/Animation Rotation Origin im Ursprung.mp4
  docs/assets/dist/interactions/08-Szenenaufbau/8.7 Hierachie/Still.jpg
  docs/assets/dist/interactions/08-Szenenaufbau/8.7 Hierachie/assets/Animation_Rotation_Origin_am_Gelenk.mp4
  docs/assets/dist/interactions/08-Szenenaufbau/8.7 Hierachie/assets/Animation_Rotation_Origin_im_Ursprung.mp4
  docs/assets/dist/interactions/08-Szenenaufbau/8.7 Hierachie/assets/Still.jpg
  docs/assets/dist/interactions/08-Szenenaufbau/8.7 Hierachie/main.css
  docs/assets/dist/interactions/08-Szenenaufbau/8.7 Hierachie/main.html
  docs/assets/dist/interactions/08-Szenenaufbau/8.7 Hierachie/main.js
  docs/assets/dist/interactions/08-Szenenaufbau/8.7 Hierachie/main.js.map
  docs/assets/dist/interactions/08-Szenenaufbau/8.7 Hierachie/main.ts
  docs/assets/dist/interactions/13-Animation/13.2 Interpolationskurven/assets/square.jpg
  docs/assets/dist/interactions/13-Animation/13.2 Interpolationskurven/main.css
  docs/assets/dist/interactions/13-Animation/13.2 Interpolationskurven/main.html
  docs/assets/dist/interactions/13-Animation/13.2 Interpolationskurven/main.js
Labels: review

#227 corrected wrong video
  docs/assets/dist/data/data.json
Labels: bug

#228 changed info text for maßeinheiten von datenmengen
  docs/assets/dist/data/data.json
Labels: bug

#229 corrected png video reference, added informations
  docs/assets/dist/data/data.json
Labels: improvement

#230 7.3 Kurven – Interaktion NEU
  Interaktionen/07-Vektorgrafik/kurvenUndSplines/main.css
  Interaktionen/07-Vektorgrafik/kurvenUndSplines/main.html
  Interaktionen/07-Vektorgrafik/kurvenUndSplines/main.js
Labels: Interaction
